### ISSUE TITLE
Problem with GUI(Buster)

### ISSUE THREAD

**Issue by wikipedia555** [RPi-Distro/pi-gen#321] opened 2019-08-05 04:02 UTC
For assembly I use the Virtual machine with Debian10. The assembly proceeds without errors, but after loading the system on raspberrypi there is a problem with the graphical interface (See the screenshots). Already collected several times, and always the same result. This problem is solved after starting the system on rasberrypi and reinstall the package "raspberrypi-ui-mods"(`sudo apt-get install --reinstall rasberrypi-ui-mods`), but this is not very convenient for my tasks.
[log.txt](https://github.com/RPi-Distro/pi-gen/files/3465883/log.txt)
![2019-08-02-092302_1600x1200_scrot](https://user-images.githubusercontent.com/38938408/62438107-f5f13c80-b713-11e9-9ba2-9d29f5b723e5.png)

**Comment by XECDesign** [comment] 2019-08-05 11:49
Duplicate of #316 and #271

**Closed by XECDesign** 2019-08-05 11:49 UTC
